export ZSH="${HOME}/.oh-my-zsh"

export LANG=en_US.UTF-8  
export LANGUAGE=en_US:en  
export LC_ALL=en_US.UTF-8

export CLICOLOR_FORCE=1
export TERM=xterm-256color

ZSH_THEME="simple"

CASE_SENSITIVE="true"

plugins=(git
         zsh-interactive-cd
         vi-mode
         alias-finder
         command-not-found
         extract
         history-substring-search
         zsh-syntax-highlighting
         zsh-autosuggestions
         )

source ${ZSH}/oh-my-zsh.sh

export EDITOR='nvim'
export VIEWER='nvim'

export PATH=${HOME}/.local/bin:${PATH}

export PATH=/usr/local/go/bin:${PATH}
export GOPATH=${HOME}/go
export PATH=${PATH}:${GOPATH}/bin

# Add cargo binaries to PATH
export PATH=${HOME}/.cargo/bin:${PATH}

# Docker settings
export DOCKER_HOST=unix:///var/run/docker.sock

alias ls="eza"

unalias colorize 2>/dev/null || true

function colorize() {
    python3 -c '
import sys
import re

# ANSI escape sequences
ESC = "\033["

# Colors
RED_FG = f"{ESC}31m"
GREEN_FG = f"{ESC}32m"
YELLOW_FG = f"{ESC}33m"
CYAN_FG = f"{ESC}36m"
GRAY_FG = f"{ESC}90m"
RESET_ALL = f"{ESC}0m"

for line in sys.stdin:
    original_line = line.rstrip("\n")
    output_parts = []

    first_char_original = original_line[0] if original_line else ""
    rest_of_line = original_line[1:] if original_line else ""

    if first_char_original == "E":
        output_parts.append(f"{RED_FG}E{RESET_ALL}")
    elif first_char_original == "W":
        output_parts.append(f"{YELLOW_FG}W{RESET_ALL}")
    elif first_char_original == "I":
        output_parts.append(f"{GREEN_FG}I{RESET_ALL}")
    else:
        if first_char_original:
            output_parts.append(first_char_original)
    
    current_text_to_process = rest_of_line
    
    bracket_pos = current_text_to_process.find("]")

    if bracket_pos != -1:
        text_before_bracket = current_text_to_process[:bracket_pos]
        text_after_bracket = current_text_to_process[bracket_pos+1:]

        processed_text_before_bracket = re.sub(r"(\d+)", f"{CYAN_FG}\\1{RESET_ALL}", text_before_bracket)
        processed_text_before_bracket = re.sub(r"\.", f"{GRAY_FG}.{RESET_ALL}", processed_text_before_bracket)
        processed_text_before_bracket = re.sub(r":", f"{GRAY_FG}:{RESET_ALL}", processed_text_before_bracket)
        
        output_parts.append(processed_text_before_bracket)
        output_parts.append(f"{GRAY_FG}]{RESET_ALL}")
        output_parts.append(text_after_bracket)
    else:
        output_parts.append(current_text_to_process)
            
    sys.stdout.write("".join(output_parts) + "\n")
    sys.stdout.flush()
'
}

rm -f ~/.colorize_log.py
