export ZSH="${HOME}/.oh-my-zsh"

export LANG=en_US.UTF-8  
export LANGUAGE=en_US:en  
export LC_ALL=en_US.UTF-8

export CLICOLOR_FORCE=1

ZSH_THEME="simple"

CASE_SENSITIVE="true"

plugins=(git
         zsh-interactive-cd
         vi-mode
         alias-finder
         command-not-found
         extract
         history-substring-search
         zsh-syntax-highlighting
         zsh-autosuggestions
         )

source ${ZSH}/oh-my-zsh.sh

export EDITOR='nvim'
export VIEWER='nvim'

export PATH=${HOME}/.local/bin:${PATH}

export PATH=${PATH}:/usr/local/go/bin
export GOPATH=${HOME}/go
export PATH=${PATH}:${GOPATH}/bin

# Docker settings
export DOCKER_HOST=unix:///var/run/docker.sock

alias ls="exa"
