export ZSH="${HOME}/.oh-my-zsh"

export LANG=en_US.UTF-8  
export LANGUAGE=en_US:en  
export LC_ALL=en_US.UTF-8

export CLICOLOR_FORCE=1
export TERM=xterm-256color

ZSH_THEME="simple"

CASE_SENSITIVE="true"

plugins=(git
         zsh-interactive-cd
         vi-mode
         alias-finder
         command-not-found
         extract
         history-substring-search
         zsh-syntax-highlighting
         zsh-autosuggestions
         )

source ${ZSH}/oh-my-zsh.sh

export EDITOR='nvim'
export VIEWER='nvim'

export PATH=${HOME}/.local/bin:${PATH}

# Add cargo binaries to PATH
export PATH=${HOME}/.cargo/bin:${PATH}

# claude
export PATH=${HOME}/.claude/local/:${PATH}

# Docker settings
export DOCKER_HOST=unix:///var/run/docker.sock

# Activate Python virtual environment
source ${HOME}/.venv/bin/activate

alias ls="eza"

sudo chmod 0666 /var/run/docker.sock
